nome = str(input('Digite seu nome completo: ')).strip()
n1 = nome.split()
print('Mutio prazer em conhecer-te!')
print('Seu primeiro nome é {}.'.format(n1[0]))
print('Seu ultimo nome é {}.'.format(n1[-1]))