m = input("Digite algo: ")
print("O tipo primitivo desse valor é " , type(m))
print("Só tem espaços? " , m.isspace())
print("É um número? " , m.isnumeric())
print("É alfabético? " , m.isalpha())
print("É alfanúmerico? " , m.isalnum())
print("Está em maiusculo? " , m.isupper())
print("Está em minusculo? " , m.islower())
print("Está capitalizada? " , m.istitle())